service: book-library-api

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-2
  environment:
    DATABASE_URL: ${env:AWS_POSTGRES_RDS_URL}


custom:
  pythonRequirements:
      useStaticCache: false
      useDownloadCache: false
      pipCmdExtraArgs:
        - "--platform manylinux2014_x86_64"
        - "--implementation cp"
        - "--python-version 3.8"
        - "--only-binary=:all:"

functions:
  app:
    handler: main.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin


package:
  patterns:
    - '.env'
    - '!.venv/**'
    - '!node_modules/**'
    - '!.git/**'