service: book-library-api

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-2
  environment:
    DATABASE_URL: ${env:AWS_POSTGRES_RDS_URL}

functions:
  app:
    handler: main.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

package:
  patterns:
    - '.env'
    - '!.venv/**'
    - '!node_modules/**'
    - '!.git/**'